<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>RxFlow.Infrastructure</RootNamespace>
    <AssemblyName>RxFlow.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RxFlow.Application\RxFlow.Application.csproj" />
    <ProjectReference Include="..\RxFlow.Domain\RxFlow.Domain.csproj" />
  </ItemGroup>
</Project>
