// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RxFlow.Infrastructure.Persistence;

#nullable disable

namespace RxFlow.Infrastructure.Migrations
{
    [DbContext(typeof(RxFlowDbContext))]
    [Migration("20260828062720_AddOutboxMessages")]
    partial class AddOutboxMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RxFlow.Domain.LensOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RxFlow.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DispatchedAt");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("RxFlow.Domain.LensOrder", b =>
                {
                    b.OwnsOne("RxFlow.Domain.Frame", "Frame", b1 =>
                        {
                            b1.Property<Guid>("LensOrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("A")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("B")
                                .HasColumnType("numeric");

                            b1.Property<string>("Id")
                                .HasColumnType("text");

                            b1.HasKey("LensOrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("LensOrderId");
                        });

                    b.OwnsOne("RxFlow.Domain.Prescription", "Prescription", b1 =>
                        {
                            b1.Property<Guid>("LensOrderId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Axis")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Cylinder")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Sphere")
                                .HasColumnType("numeric");

                            b1.HasKey("LensOrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("LensOrderId");
                        });

                    b.Navigation("Frame")
                        .IsRequired();

                    b.Navigation("Prescription")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
